### PR TITLE
8.0.19

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Resolves https://github.com/conda-forge/mysql-feedstock/issues/6

@beckermr As promised, I present to you the grand split recipe.

Once this is merged, we'll finally be able to build newer versions of mysql-connector-python.

The Windows build will require a re-trigger after https://github.com/conda-forge/libevent-feedstock/pull/17

### CODE REVIEW

**Comment by hmaarrfk** [comment]
is `mysqld` always returning an error code on windows?? This seems to happen quite often in many programs i've bee building

Why is that?
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=177277&view=logs&j=f97ca392-d626-52d0-4b2e-4b27aa319a77&t=7b750183-140d-50ae-3ee1-cbef6218bdf6&l=12118

**Comment by nehaljwani** [comment]
No @hmaarrfk , it is failing because it is blocked on https://github.com/conda-forge/libevent-feedstock/pull/17 . It is not able to find the DLL: `event_core.dll` in `PATH`.

**Comment by beckermr** [comment]
@conda-forge-admin restart ci

**Comment by nehaljwani** [comment]
And ... we have a green light! Finally!

**Comment by beckermr** [comment]
Shall we merge?

**Comment by nehaljwani** [comment]
You are the current maintainer, choice is yours! 😜

**Pull request merged**
