### PR TITLE
Rebuild lz4

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes https://github.com/conda-forge/mysql-feedstock/pull/27

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Building on a ppc64le machine, I get the following error message:

```
[2402/2407] Linking CXX executable runtime_output_directory/mysqld
FAILED: runtime_output_directory/mysqld 
: && $BUILD_PREFIX/bin/powerpc64le-conda-linux-gnu-c++ -std=c++14 -fno-omit-frame-pointer -ffp-contract=off -ftls-model=initial-exec -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/mysql-suite-8.0.22 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wall -Wextra -Wformat-security -Wvla -Wundef -Wmissing-format-attribute -Woverloaded-virtual -Wcast-qual -Wimplicit-fallthrough=2 -Wstringop-truncation -Wsuggest-override -Wlogical-op -DDBUG_OFF -ffunction-sections -fdata-sections -O3 -DNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib   -Wl,--export-dynamic -rdynamic sql/CMakeFiles/mysqld.dir/main.cc.o -o runtime_output_directory/mysqld  -lpthread  sql/libsql_main.a  sql/libsql_gis.a  sql/libbinlog.a  sql/librpl.a  sql/libmaster.a  sql/libslave.a  sql/libsql_dd.a  archive_output_directory/libmysys.a  components/libminchassis/libminchassis.a  libbinlogevents/lib/libbinlogevents.a  $PREFIX/lib/libicuuc.so  $PREFIX/lib/libicuio.so  $PREFIX/lib/libicudata.so  $PREFIX/lib/libicui18n.so  storage/innobase/libinnobase.a  sql/libsql_main.a  sql/libsql_gis.a  sql/libbinlog.a  sql/librpl.a  sql/libmaster.a  sql/libslave.a  sql/libsql_dd.a  storage/innobase/libinnobase.a  sql/libsql_main.a  sql/libsql_gis.a  sql/libbinlog.a  sql/librpl.a  sql/libmaster.a  sql/libslave.a  sql/libsql_dd.a  storage/innobase/libinnobase.a  storage/archive/libarchive.a  storage/blackhole/libblackhole.a  storage/csv/libcsv.a  storage/federated/libfederated.a  storage/heap/libheap.a  storage/heap/libheap_library.a  storage/myisam/libmyisam.a  storage/myisam/libmyisam_library.a  storage/myisammrg/libmyisammrg.a  storage/perfschema/libperfschema.a  storage/temptable/libtemptable.a  plugin/fulltext/libngram_parser.a  plugin/x/libmysqlx.a  $PREFIX/lib/libevent_core.so  $PREFIX/lib/libevent_extra.so  $PREFIX/lib/libevent_openssl.so  $PREFIX/lib/libevent_pthreads.so  $PREFIX/lib/libicuuc.so  $PREFIX/lib/libicuio.so  $PREFIX/lib/libicudata.so  $PREFIX/lib/libicui18n.so  plugin/x/protocol/protobuf/libmysqlxmessages_lite.a  $PREFIX/lib/libprotobuf-lite.so  sql/server_component/libmysql_server_component_services.a  archive_output_directory/libvio.a  -lcrypt  libbinlogevents/lib/libbinlogevents.a  archive_output_directory/libmysys.a  archive_output_directory/libstrings.a  archive_output_directory/libmysys.a  archive_output_directory/libstrings.a  archive_output_directory/libmytime.a  -lm  -lrt  $PREFIX/lib/libssl.so  $PREFIX/lib/libcrypto.so  -ldl  $PREFIX/lib/libzstd.so  $PREFIX/lib/libz.so  $PREFIX/lib/liblz4.so  -lpthread && :
plugin/x/libmysqlx.a(socket_events.cc.o): in function `ngs::Socket_events::socket_data_avaiable(int, short, void*)':
socket_events.cc:(.text._ZN3ngs13Socket_events20socket_data_avaiableEisPv+0x504): relocation truncated to fit: R_PPC64_REL24 against symbol `std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()' defined in .text._ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv[_ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv] section in sql/libsql_main.a(opt_range.cc.o)
socket_events.cc:(.text._ZN3ngs13Socket_events20socket_data_avaiableEisPv+0x524): relocation truncated to fit: R_PPC64_REL24 against symbol `std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()' defined in .text._ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv[_ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv] section in sql/libsql_main.a(opt_range.cc.o)
sql/libsql_main.a(mysqld_thd_manager.cc.o): in function `inline_mysql_mutex_unlock(mysql_mutex_t*, char const*, unsigned int) [clone .isra.0]':
mysqld_thd_manager.cc:(.text.unlikely._ZL25inline_mysql_mutex_unlockP13mysql_mutex_tPKcj.isra.0+0x40): relocation truncated to fit: R_PPC64_REL24 against symbol `pfs_unlock_mutex_v1(PSI_mutex*)' defined in .text._Z19pfs_unlock_mutex_v1P9PSI_mutex section in storage/perfschema/libperfschema.a(pfs.cc.o)
sql/libsql_main.a(mysqld_thd_manager.cc.o): in function `Find_thd_with_id::operator()(THD*)':
mysqld_thd_manager.cc:(.text._ZN16Find_thd_with_idclEP3THD+0xb8): relocation truncated to fit: R_PPC64_REL24 against symbol `pfs_start_mutex_wait_v1(PSI_mutex_locker_state_v1*, PSI_mutex*, PSI_mutex_operation, char const*, unsigned int)' defined in .text._Z23pfs_start_mutex_wait_v1P25PSI_mutex_locker_state_v1P9PSI_mutex19PSI_mutex_operationPKcj section in storage/perfschema/libperfschema.a(pfs.cc.o)
mysqld_thd_manager.cc:(.text._ZN16Find_thd_with_idclEP3THD+0xfc): relocation truncated to fit: R_PPC64_REL24 against symbol `pfs_end_mutex_wait_v1(PSI_mutex_locker*, int)' defined in .text._Z21pfs_end_mutex_wait_v1P16PSI_mutex_lockeri section in storage/perfschema/libperfschema.a(pfs.cc.o)
sql/libsql_main.a(mysqld_thd_manager.cc.o): in function `Global_THD_manager::Global_THD_manager()':
mysqld_thd_manager.cc:(.text._ZN18Global_THD_managerC2Ev+0x19c): relocation truncated to fit: R_PPC64_REL24 against symbol `pfs_register_mutex_v1(char const*, PSI_mutex_info_v1*, int)' defined in .text._Z21pfs_register_mutex_v1PKcP17PSI_mutex_info_v1i section in storage/perfschema/libperfschema.a(pfs.cc.o)
mysqld_thd_manager.cc:(.text._ZN18Global_THD_managerC2Ev+0x1c0): relocation truncated to fit: R_PPC64_REL24 against symbol `pfs_register_cond_v1(char const*, PSI_cond_info_v1*, int)' defined in .text._Z20pfs_register_cond_v1PKcP16PSI_cond_info_v1i section in storage/perfschema/libperfschema.a(pfs.cc.o)
mysqld_thd_manager.cc:(.text._ZN18Global_THD_managerC2Ev+0x1f4): relocation truncated to fit: R_PPC64_REL24 against symbol `pfs_init_mutex_v1(unsigned int, void const*)' defined in .text._Z17pfs_init_mutex_v1jPKv section in storage/perfschema/libperfschema.a(pfs.cc.o)
mysqld_thd_manager.cc:(.text._ZN18Global_THD_managerC2Ev+0x244): relocation truncated to fit: R_PPC64_REL24 against symbol `pfs_init_mutex_v1(unsigned int, void const*)' defined in .text._Z17pfs_init_mutex_v1jPKv section in storage/perfschema/libperfschema.a(pfs.cc.o)
mysqld_thd_manager.cc:(.text._ZN18Global_THD_managerC2Ev+0x288): relocation truncated to fit: R_PPC64_REL24 against symbol `pfs_init_cond_v1(unsigned int, void const*)' defined in .text._Z16pfs_init_cond_v1jPKv section in storage/perfschema/libperfschema.a(pfs.cc.o)
mysqld_thd_manager.cc:(.text._ZN18Global_THD_managerC2Ev+0x2e0): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status

```

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@conda-forge/mysql this is ready for review. I had to downgrade the compiler since it seems like a compiler error.

Do you think there might be any unintended consequences downstream?

This migration is holding up a few other PRs.

**Comment by nehaljwani** [comment]
@conda-forge-admin, please Re-render!

**Pull request merged**
