### PR TITLE
Upgrade to version 8.0.20

### PR DESCRIPTION
**Pull request by AgrawalAmey**
Checklist
* [y ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [y ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by AgrawalAmey** [comment]
@conda-forge-admin, please rerender

**Comment by AgrawalAmey** [comment]
@nehaljwani, please suggest any improvements for the build

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by nehaljwani** [comment]
I have a pull request for this at https://github.com/conda-forge/mysql-feedstock/pull/8

**Pull request closed without merging**
