### PR TITLE
Aarch

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I guess @nehaljwani used cross compilation because this is a slow package to build.

I wonder if we will get lucky and have "fast" aarch machines, or "slow" ones.

**Comment by hmaarrfk** [comment]
Right in the nick of time. 54 mins / 60.

**Comment by beckermr** [comment]
yes @hmaarrfk - there is one fast one and one slow one

@isuruf and I see this when building compilers

**Comment by hmaarrfk** [comment]
Is it accetable that it works in 54/60 mins? or would you like us to cross compile again?

**Comment by nehaljwani** [comment]
I would cross compile. Life's too short to deal with slow machines :wink:

**Comment by nehaljwani** [comment]
For ppc64le, it always crossed the time limit, so I had given up on it and resorted on cross compile.

**Comment by nehaljwani** [comment]
Ah, this passed the CI, finally! Alright, we can switch to cross if it gives us pain in the future, for now, I'll merge it!

**Comment by beckermr** [comment]
🤞 we get the fast machine with the build on master...

**Comment by nehaljwani** [comment]
We were lucky, the one in master finished in 23 mins :stuck_out_tongue_winking_eye:

**Comment by hmaarrfk** [comment]
nice

**Pull request merged**
